### PR TITLE
Trap TERM to allow quicker exit of web containers

### PR DESCRIPTION
**Pull request by md5**
This cut the test time roughly in half for me locally.

### CODE REVIEW

**Comment by md5** [comment]
This doesn't seem to have had quite as dramatic an effect on CircleCI as it had locally... Let me know if you just want me to close it.

**Comment by jwilder** [comment]
I see the same speed ups locally as well so definitely a worthwhile change.

**Comment by jwilder** [comment]
Thanks @md5!

**Comment by md5** [comment]
Cool. :+1:

**Pull request merged**
