### PR TITLE
Upgrade to nginx 1.11.10

### PR DESCRIPTION
**Pull request by matt-hh**
http://nginx.org/en/CHANGES

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_background_update
http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_use_stale

### CODE REVIEW

**Comment by matt-hh** [comment]
Both tests work on my local machine (Docker version 1.13.1).

```
$ make test

test_dockergen/test_dockergen_v3.py::test_unknown_virtual_host_is_503 PASSED
test_dockergen/test_dockergen_v3.py::test_forwards_to_whoami PASSED
```

@thomasleveil Can you help please?

**Comment by thomasleveil** [comment]
@matt-hh tests also pass on my machine. There is nothing to worry about with your changes. I guess the retry mechanism I implemented on the test suite isn't suited for all cases, I'll see what I can do.

In the meantime, this PR is safe to merge. 

If you want to force Travis-CI to build this PR again, you could make a minor change (like whitespace change, typo fix, ...) in your code, `git commit --amend` and then `git push origin feature/upgrade-1.11.10:feature/upgrade-1.11.10 --force` to update the PR.

**Comment by thomasleveil** [comment]
@matt-hh bad luck Travis CI had network issues this time :/

**Comment by matt-hh** [comment]
@thomasleveil It works now... Thank you for your help.

**Comment by jwilder** [comment]
Thanks @matt-hh!

**Pull request merged**
