### PR TITLE
Remove duplicate access log entries

### PR DESCRIPTION
**Pull request by md5**
After getting some advice over at https://github.com/nginxinc/docker-nginx/issues/39#issuecomment-137470214, I managed to fix this issue.

Fixes #216

### CODE REVIEW

**Comment by md5** [comment]
cc/ @wader @jgallen23

**Comment by jgallen23** [comment]
awesome!  thanks @md5

**Comment by wader** [comment]
nice, thanks @md5. Closed my PR.

**Comment by md5** [comment]
Ping @jwilder

**Comment by jwilder** [comment]
Thanks @md5!

**Comment by md5** [comment]
:+1:

**Pull request merged**
