### PR TITLE
Updates for 0.7.0 release

### PR DESCRIPTION
**Pull request by jwilder**

### CODE REVIEW

**Comment by jwilder** [comment]
@thomasleveil Any idea what might have broke in the tests recently?

**Comment by thomasleveil** [comment]
Have you tried when keeping the python Docker module to v2.0.2?

 `docker==2.0.2`

**Comment by jwilder** [comment]
I was getting a different error before and that seemed to resolve it.  I reverted it now.

**Comment by thomasleveil** [comment]
Try `git revert 4aa396e7` (or `rebase -i` to get rid of 4aa396e7)

I also see a warning on Travis CI log stating they upgraded their stack:

> This job ran on our Trusty environment, which has been updated on Tuesday, December 12th, 2017. Read all about this on our blog and take note that you can add group: deprecated-2017Q4 in your .travis.yml file to use the previous image version.

Maybe that's also part of the issue

**Pull request merged**
