### PR TITLE
Update to nginx 1.9.7

### PR DESCRIPTION
**Pull request by j16sdiz**

### CODE REVIEW

**Comment by JamieMagee** [comment]
nginx is currently at 1.9.9 now.

**Comment by md5** [comment]
@JamieMagee The latest update for the Docker image is 1.9.8: https://github.com/nginxinc/docker-nginx/commit/a19bdf994ab1a5960b998574cf6fcc410992b6ff

**Comment by JamieMagee** [comment]
Whoops, my bad. I was just going by the version on the nginx website. I
expect the Docker will be updated shortly.

**Comment by md5** [comment]
I just opened a PR to update it: https://github.com/nginxinc/docker-nginx/pull/53

**Comment by md5** [comment]
`nginx:1.9.9` is up on Docker Hub.

**Comment by sdurrheimer** [comment]
The image is now based on `nginx:1.9.12`, this PR can be closed.

**Pull request closed without merging**
