### PR TITLE
optional IPv6 support

### LINKED ISSUE #127: IPv6 Support
Hi.
Would it be possible to add an option, which adds a listen directive for IPv6?

### LINKED ISSUE #717: Unable to start due to IPv6 binding
After #713 was merged yesterday, I am unable to start `nginx-proxy` on unRAID, as its kernel is not compiled with IPv6 support. I get the following error message:

`[emerg] 18#18: socket() [::]:80 failed (97: Address family not supported by protocol)`

There is currently an [open feature request](https://lime-technology.com/forum/index.php?topic=39533.0) to compile the kernel unRAID uses with IPv6 support. I am sure that unRAID is not the only OS that doesn't have full IPv6 support yet.

Is it possible to either:
1. Rollback change #713 
2. Create an IPv4 only docker tag `nginx-proxy`

### PR DESCRIPTION
**Pull request by thomasleveil**
Fix #127 and fix #717 by improving #713

### CODE REVIEW

**Comment by JamieMagee** [comment]
This is even better than either of my suggestions!

It looks like the build failed because is couldn't install `bats`. Maybe you can retry the build?

**Comment by thomasleveil** [comment]
I can't restart the Travis-CI builds, but I will force push to this PR to trigger it again. On my computer all bats tests pass.

**Comment by JamieMagee** [comment]
It passed this time. Hopefully @jwilder can merge this PR soon.

**Comment by schrieveslaach** [comment]
Just awesome, @thomasleveil

**Comment by jwilder** [comment]
Thanks @thomasleveil!

**Pull request merged**
