### PR TITLE
Add HSTS header regardless of status code

### PR DESCRIPTION
**Pull request by b1f6c1c4**
See nginx [doc](http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header) and [blog](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/).

### CODE REVIEW

**Comment by kamermans** [comment]
Once b1f6c1c4/nginx-proxy#2 is merged there, this will be covered by tests and it will LGTM.

**Comment by Archcry** [comment]
Ready to go!

**Comment by kamermans** [comment]
Thanks @archcry!  @jwilder, this bugfix looks good to me.

**Comment by Archcry** [comment]
Well it wasn't actually me who wrote the pull-request :P

**Comment by b1f6c1c4** [comment]
@kamermans so this PR can be merged, right?

**Comment by kamermans** [comment]
Oops, I meant thanks @b1f6c1c4, and yes, it can (in my opinion).

**Pull request merged**
