### PR TITLE
Use container host's IP:port if we're connected to a swarm master

### PR DESCRIPTION
**Pull request by viranch**
This PR completes support for Swarm cluster.

This will also pick up any containers running on a remote host that is in the Swarm cluster and uses the host address/port instead of container address/port.

### CODE REVIEW

**Comment by md5** [comment]
LGTM

That being said, this section of the template is getting to be pretty unmaintainable. It might be nice to use `{{define}}` and `{{template}}` to streamline some of the repetitive parts, though I'm not sure how much that would help.

**Comment by viranch** [comment]
@md5 +1.

I started off by assigning the address object to a `chosenAddr` variable and doing swarm logic outside the if-else, but couldn't get it to work.

**Comment by viranch** [comment]
Ping.

Added `{{define}}` & `{{template}}` for upstream block. Also a simplification to `coalesce .Env.VIRTUAL_PORT "80"` to reduce an `else` block (check commit diffs).

**Comment by md5** [comment]
:+1:

**Comment by jwilder** [comment]
@viranch Haven't had a chance to test this yet but want to get it merged. @md5 Thanks for reviewing.  If anyone else could help test this PR out with their existing setup that would be very useful.

**Comment by viranch** [comment]
If it helps, I'm using this patch in production, after thorough testing of course :)

**Comment by jwilder** [comment]
Thanks @viranch!

**Pull request merged**
