### PR TITLE
Support static file serving

### PR DESCRIPTION
**Pull request by iddo**
Easy to use static file serving alongside the reverse proxy using the 'try_files' directive with named location technique

### CODE REVIEW

**Comment by kytwb** [comment]
Can this get merged?

**Comment by iddo** [comment]
It's pretty straight forward, so I definitely think so, but I'm not the one calling the shots around here :-)

**Comment by kytwb** [comment]
Ping @jwilder

**Comment by thomasleveil** [comment]
shouldn't this proxy project stay focused on its mission: _Automated nginx proxy for Docker containers using docker-gen_?

This would add a new role (webserver) to this project. I like projects that do less but do it right (UNIX philosophy). 

If one needs to serve static files, I suggest the use of a container that does the job of serving file in combination with nginx-proxy and not changing nginx-proxy

**Comment by iddo** [comment]
Normally I would agree with what @thomasleveil wrote, "use specialized tools for every need", but there aren't that many static file serving options out there (https://nbonvin.wordpress.com/2011/03/14/apache-vs-nginx-vs-varnish-vs-gwan/) and this is quite a common scenario.
Achieving this kind of configuration (static files with fallback to the reverse proxy) will still require specialized nginx (or other) configuration even if we were to use a specialized static file server.

**Comment by thaJeztah** [comment]
Now that nginx-proxy supports per virtual-host configuration files, I don't really see a reason to add this to the default template. Also, it's possible to replace the default template either by bind-mounting it as a volume, or creating a simple Dockerfile that extends the image.

I'm sure there are people that want this, but not *everyone*. How about an "examples" directory in the repository, accompanied by a README.md that explains what each example does?

**Comment by iddo** [comment]
@thaJeztah, I'm using the bind-mount technique with my suggested template modification, but given the default behavior does not change for people who don't need/use this feature I think it will be a welcomed addition.

**Comment by md5** [comment]
I'm on the fence on this one. Setting up `nginx-proxy` + an app + another `nginx` can be kind of tricky in terms of getting the virtual host stuff right. Without multiple paths supports (cf. #47), you'd either have to only use `VIRTUAL_HOST` on the `nginx` container that is itself proxying to the app or you'd have to arrange for the static assets to be served from a separate hostname.

**Comment by jwilder** [comment]
I agree with @thaJeztah and @thomasleveil .  Since it is possible to do this with the current features, I think it's better to keep the project focused on a being a proxy for now and add examples or documentation on how to set this up if needed.  Static file serving will likely require other customization hooks for cache control, compression, etc. that I would rather not support right now.

**Comment by tanzaho** [comment]
Can anyone give some hints about how to proceed ?

**Comment by thomasleveil** [comment]
See https://github.com/jwilder/nginx-proxy/blob/master/README.md#per-virtual_host

**Comment by tanzaho** [comment]
I followed the instructions, and I tried to add the following to nginx.
``` 
location /static/ {
	/usr/src/app/static/;
    }
``` 
These where added as a volume named as the host.

When I restarted nginx_proxy, the file was used, but the behavior is not the one I expected : 
* the index page is not showing my app anymore, instead it shows the "Welcome to nginx". 
* the /static/ folder returns a 404.

I know that my question might be related to nginx, but if anyone can point me toward the good direction, that'd very nice.

PS : I am using docker-compose to run my containers.

**Comment by pascalandy** [comment]
@tanzaho Hey Jean-Christophe! May I asked you back to question you asked a year ago ?

> I know that my question might be related to nginx, but if anyone can point me toward the good direction, that'd very nice.

**Pull request closed without merging**
