### PR TITLE
Allow vhosts to serve both http and https.

### PR DESCRIPTION
**Pull request by darrint**
I needed this for testing a site that handled both http and https.

### CODE REVIEW

**Comment by sdurrheimer** [comment]
+1 for this kind of feature

**Comment by patakijv** [comment]
+1 : this seems like it is a must have unless there is another way to avoid having 100% of your traffic be routed through HTTPS.

**Comment by genezys** [comment]
PR #298 seems to have a more complete solution.

**Comment by sdurrheimer** [comment]
#298 has been merged, this PR can be closed.

**Pull request closed without merging**
