### PR TITLE
Add gRPC protocol support (#1345)

### PR DESCRIPTION
**Pull request by umevoshi**

### CODE REVIEW

**Comment by pjvds** [comment]
Is the ngx_http_grpc_module available by default?

**Comment by umevoshi** [comment]
> Is the ngx_http_grpc_module available by default?
yes, gRPC Support  with NGINX 1.13.10
https://www.nginx.com/blog/nginx-1-13-10-grpc/

**Comment by cosullivan** [comment]
Can this get merged? I am keen to have gRPC support too.

Thanks,
Cain.

**Comment by los93sol** [comment]
Will this ever get merged?

**Comment by los93sol** [comment]
Anyone still maintaining this repo?

**Comment by moul** [comment]
cc @jwilder

**Comment by buchdag** [comment]
@ptflp unfortunately no, looks like an oversight when this was added.

It works by setting the environment variable `VIRTUAL_PROTO` to `grpc` on the proxied container (like the [SSL backend](https://github.com/nginx-proxy/nginx-proxy#ssl-backends) feature).

This feature does not have integration tests and is rarely mentioned, so your input would be welcome.

**Comment by buchdag** [comment]
@maratkalibek would this be enough ?

> ### gRPC / gRPCS Upstream
>
> If you would like to connect to a gRPC or gRPCS backend, set either `VIRTUAL_PROTO=grpc` or `VIRTUAL_PROTO=grpcs` on the backend container.

**Pull request merged**
