### PR TITLE
Remove TLS 1.0 for PCI compliance

### PR DESCRIPTION
**Pull request by buchdag**
TLS 1.0 has finally been EOL'd by PCI on 30/04/2018: https://payment-services.ingenico.com/int/en/ogone/support/products/tls

### CODE REVIEW

**Comment by buchdag** [comment]
Any issue with this PR ?

**Comment by kamermans** [comment]
I was going to do the same thing in my SSL Enhancements PR #589, but I found that there were still a fair number of devices using TLS 1.0.  I will look through a few billion client requests today and post what percentage of my traffic is still on TLS 1.0.

**Comment by kamermans** [comment]
I'll run the numbers on a bigger sample at some point, but here's a quick sample of `315626` HTTPS requests:

```
 313098 TLSv1.2 (99.19%)
   2110 TLSv1.0 (0.67%)
    418 TLSv1.1 (0.14%)
```
My traffic sample was taken today from a US load balancer, and it represents primarily traffic from North and South America.  Things are probably slightly better in Europe and possibly much worse in Southeast Asia and Africa.

All in all, most people are probably just fine using only TLS 1.2+, but at least for me, I'm not sure I'd be able to drop that 1% of traffic yet, since my customers are paying me for the web services I provide.

Here's an example of the types of clients connecting to me with TLS 1.0:

```
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Win64; x64; Trident/6.0)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; Win64; x64; Trident/6.0)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/6.0; Touch)
Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; 909)
Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; Lumia 920)
Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; SAMSUNG; SCH-I930)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0; MSN Optimized;ENCA)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0;  Trident/5.0)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0; EIE10;ENUSWOL)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0;  Trident/5.0)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)
Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SOPREMA)
Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; SAMSUNG; GT-I8750)
Mozilla/5.0 (iPad; CPU OS 5_0_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A405 Safari/7534.48.3
Mozilla/5.0 (iPad; CPU OS 6_0 like Mac OS X) AppleWebKit/536.26 (KHTML, like Gecko) Version/6.0 Mobile/10A5355d Safari/8536.25
Mozilla/5.0 (iPad; CPU OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Version/7.0 Mobile/11D257 Safari/9537.53
Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B367 Safari/531.21.10
Mozilla/5.0 (iPhone; CPU iPhone OS 5_0 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9A334 Safari/7534.48.3
Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_5 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8L1 Safari/6533.18.5
Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SM-T210R Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SM-T211 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SM-T217S Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SPH-L710 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SPH-L900 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; es-es; DROIDZ Point Build/JZO54K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; es-es; SM-G355M Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; es-us; GT-N7100 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; es-us; SM-G313F Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; es-us; SM-G313M Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; es-us; SM-G355M Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; es-us; SM-T210 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; pt-br; SM-G313M Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; pt-br; SM-G313MU Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; pt-br; SM-G355M Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; pt-br; SM-T210 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Linux; U; Android 4.4.2; pt-br; SM-T211 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) Version/6.0.3 Safari/536.28.10
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.76.4 (KHTML, like Gecko) Version/6.1.4 Safari/537.76.4
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.77.4 (KHTML, like Gecko) Version/6.1.5 Safari/537.77.4
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/6.2.8 Safari/537.85.17
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_4_11; en) AppleWebKit/533.19.4 (KHTML, like Gecko) Version/4.1.3 Safari/533.19.4
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_7; en-us) AppleWebKit/530.17 (KHTML, like Gecko) Version/4.0 Safari/530.17
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; en-us; Silk/1.0.146.3-Gen4_12000410) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Safari/533.16 Silk-Accelerated=false
Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_3; en-us; Silk/1.0.146.3-Gen4_12000410) AppleWebKit/533.16 (KHTML, like Gecko) Version/5.0 Safari/533.16 Silk-Accelerated=true
Mozilla/5.0 (SMART-TV; Linux; Tizen 2.3) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.0 TV Safari/538.1
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.0 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36
Mozilla/5.0 (X11; CrOS x86_64 9592.85.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.112 Safari/537.36
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.34 Safari/534.24
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:29.0) Gecko/20100101 Firefox/29.0
Nokia2700c-2/2.0 (07.15) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; en-US; Nokia2700c-2) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile
Nokia302/5.0 (14.26) Profile/MIDP-2.1 Configuration/CLDC-1.1 UCWEB/2.0 (Java; U; MIDP-2.0; vi; Nokia302) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile UNTRUSTED/1.0
Opera/9.80 (BREW; Opera Mini/5.1/27.2414; U; en) Presto/2.8.119 240X320 Casio C781
UCWEB/2.0 (Java; U; MIDP-2.0; en-US; SAMSUNG-GT-S5753E) U2/1.0.0 UCBrowser/9.5.0.449 U2/1.0.0 Mobile UNTRUSTED/1.0
UCWEB/2.0 (Java; U; MIDP-2.0; Nokia203/20.37) U2/1.0.0 UCBrowser/8.7.0.218 U2/1.0.0 Mobile
UCWEB/2.0 (Linux; U; Opera Mini/7.1.32052/30.3697; en-US; G928) U2/1.0.0 UCBrowser/9.6.0.514 Mobile
UCWEB/2.0 (Linux; U; Opera Mini/7.1.32052/30.3697; en-US; GT-I9100 Build/GINGERBREAD) U2/1.0.0 UCBrowser/10.7.9.856 Mobile
UCWEB/2.0 (Linux; U; Opera Mini/7.1.32052/30.3697; es-LA; Sony-Z3 Build/KOT49H) U2/1.0.0 UCBrowser/10.7.5.785 Mobile
UCWEB/2.0 (MIDP-2.0; U; Adr 4.1.2; en-US; Nokia_X) U2/1.0.0 UCBrowser/10.9.0.946 U2/1.0.0 Mobile
UCWEB/2.0 (MIDP-2.0; U; Adr 4.2.1; id; 2013022) U2/1.0.0 UCBrowser/10.7.9.856 U2/1.0.0 Mobile
UCWEB/2.0 (MIDP-2.0; U; Adr 4.2.2; en-US; HUAWEI_Y330-U01) U2/1.0.0 UCBrowser/10.7.6.805 U2/1.0.0 Mobile
UCWEB/2.0 (MIDP-2.0; U; Adr 4.4.2; en-US; HTC_Desire_620G_dual_sim) U2/1.0.0 UCBrowser/10.9.8.1006 U2/1.0.0 Mobile
UCWEB/2.0 (MIDP-2.0; U; Adr 4.4.2; en-US; SM-G7102) U2/1.0.0 UCBrowser/10.9.5.983 U2/1.0.0 Mobile
UCWEB/2.0 (MIDP-2.0; U; Adr 5.0.2; en-US; InFocus_M260) U2/1.0.0 UCBrowser/10.9.5.983 U2/1.0.0 Mobile
```
Due to the data source I used, the above clients are almost all real users.

**Comment by buchdag** [comment]
Keeping the most compatible (within acceptable security margins) default config makes perfect sense.

Removing TLS 1.0 from the template is easy enough, should editing the template be suggested in the doc for those wanting PCI compliance or higer Qualys SSL Test score ?

**Comment by kamermans** [comment]
Sure, I'm not sure how much @jwilder wants in the README, but to me it makes sense to have a subsection of the SSL section that describes how to get an A+ SSL rating with `nginx-proxy`.

For completeness, here is a breakdown of the TLS traffic that I've seen today by continent (over millions of requests):
```
North America
  TLSv1.0 0.58%
  TLSv1.1 0.1%
  TLSv1.2 99.32%
Asia
  TLSv1.0 1.27%
  TLSv1.1 0.45%
  TLSv1.2 98.28%
Oceania
  TLSv1.0 2.29%
  TLSv1.1 0.18%
  TLSv1.2 97.53%
Europe
  TLSv1.0 1.16%
  TLSv1.1 0.29%
  TLSv1.2 98.55%
South America
  TLSv1.0 1.09%
  TLSv1.1 0.27%
  TLSv1.2 98.64%
Africa
  TLSv1.0 3.86%
  TLSv1.1 0.64%
  TLSv1.2 95.5%
```

**Pull request closed without merging**
