### PR TITLE
upgrade nginx to 1.11.3

### PR DESCRIPTION
**Pull request by huiwang**
There is a known bug as described here https://stackoverflow.com/questions/36907767/nsurlerrordomain-code-1004-for-few-seconds-after-app-start-up/37444271#37444271

One solution is to upgrade nginx to 1.11.0 http://stackoverflow.com/a/37444404/341307

### CODE REVIEW

**Comment by bartoszhernas** [comment]
+1 for immediate merge. I am expecting the same problem right now.

**Comment by joe11051105** [comment]
+1

**Comment by auchri** [comment]
Why not update to [1.11.3](https://nginx.org/en/CHANGES)?

**Comment by SeerUK** [comment]
It looks like [1.11.1](https://hub.docker.com/r/library/nginx/tags/) is the latest officially released Docker image to base this off of, @auchri.

**Comment by bernex** [comment]
+1

**Comment by tve** [comment]
There is an official nginx 1.11.3 docker image. I would also appreciate an upgrade to this version. I had to fork and do it myself in order to fix http/2 issues with nginx pre-1.11.0. Thanks!

**Comment by SeerUK** [comment]
The image has since been updated. Let's just assume that whenever this happens it'll be to whatever the latest mainline version of Nginx is.

**Comment by jwilder** [comment]
@huiwang Can you bump this to `1.11.3`?

**Comment by auchri** [comment]
I think it should be changed in https://github.com/jwilder/nginx-proxy/blob/master/Makefile too

**Comment by huiwang** [comment]
@auchri thx for your advice, @jwilder done !

**Comment by jwilder** [comment]
Thanks @huiwang!

**Pull request merged**
