### PR TITLE
Trim $host and $proto before they're used

### PR DESCRIPTION
**Pull request by md5**
This is a follow-up for #262

### CODE REVIEW

**Comment by md5** [comment]
Looks like I need to look at this more closely... Sorry for the noise.

**Comment by md5** [comment]
Got this passing. There was an issue with the fact that `first` returns `interface{}` while `trim` only deals with `string`.

**Comment by md5** [comment]
I'm not sure if this PR needs some updates despite saying it will merge, but I just saw another PR with `trim $proto` at #323

**Comment by md5** [comment]
I'd like to close this PR since it's been sitting around for over a year, but it looks like the `$host` variable is still not being trimmed. I can refresh this PR if it's going to be merged, but otherwise I'd like to close it.

**Comment by jwilder** [comment]
@md5 Sorry.  Fell off my radar. If you can rebase, I'll merge it.

**Comment by jwilder** [comment]
I pulled these changes into a new PR here: https://github.com/jwilder/nginx-proxy/pull/847

**Comment by md5** [comment]
👍

**Pull request closed without merging**
