### PR TITLE
Feature: Listen Ports for HTTP/HTTPS

### PR DESCRIPTION
**Pull request by pauldorn**
Currently ports 80 and 443 are hard coded for HTTP and HTTPS respectively.
Many applications run on non-standard ports.  This change allows a per VHost change of the defaults by including the following Env values on the VHOST container:
VIRTUAL_LISTEN_HTTP
VIRTUAL_LISTEN_HTTPS

### CODE REVIEW

**Comment by pauldorn** [comment]
Found better approach.  Closing this outdated effort.

**Comment by stevenmunro** [comment]
What was the better approach? I'm looking for this.

**Comment by jacobdorn** [comment]
See wsbu/nginx-proxy

**Comment by pauldorn** [comment]
See wsbu/nginx-proxy

**Pull request closed without merging**
