### PR TITLE
Added support for Networks struct to be use it with compose-files version 1.6

### PR DESCRIPTION
**Pull request by diginikkari**
Changed DOCKER_GEN_VERSION to 0.6.0
Needed newer version to support Networks struct

Changed nginx.tmpl to use Networks -struct to get the IP -address.

### CODE REVIEW

**Comment by wader** [comment]
Will this still work with older version of docker without the new network feature?

**Comment by diginikkari** [comment]
No it was not working with older docker. I made new commit with support to older docker.

**Comment by md5** [comment]
See #337, which is waiting on https://github.com/jwilder/docker-gen/pull/158

**Comment by diginikkari** [comment]
Yep, #337 seems to be much complete solution to support networks. I will close this and wait for the merge #337 and jwilder/docker-gen#158

**Pull request closed without merging**
