### PR TITLE
Add TLSv1.3 support

### PR DESCRIPTION
**Pull request by kamermans**
As noted by @Archcry in #1108, `nginx-proxy` does not support TLSv1.3.  I'm not 100% sure of the status of TLSv1.3, but it appears to be an approved draft, which means it will be finalized eventually.  **This PR adds support for TLSv1.3**

Nginx [added support for TLS 1.3 in `1.13.0`](http://mailman.nginx.org/pipermail/nginx-announce/2017/000195.html), so it is available to `nginx-proxy` today.  The included `SSL_POLICY` options are a reflection of the policies provided by Mozilla and AWS.  Presumably, they will both add TLS 1.3 to all of their policies, although I suppose they could decide not to include it for unknown reasons.  It appears they are [waiting for the draft to be finalized](https://github.com/awslabs/s2n/issues/388) before announcing support.

I think it is reasonable for us to add support already today since all of our SSL/TLS policies include the latest version of TLS, and it's hard to imagine why we would not want people to be able to use it.

### CODE REVIEW

**Comment by Archcry** [comment]
Any progress on this?

**Comment by kamermans** [comment]
It's finished and ready to go.  Do you want to include TLSv1.3 support @jwilder?

**Comment by Archcry** [comment]
I know I do :)

**Comment by Archcry** [comment]
@jwilder, can we merge this?

**Pull request merged**
