### PR TITLE
fix fastcgi bug

### PR DESCRIPTION
**Pull request by qiqizjl**
fix fastcgi bug for debian

### CODE REVIEW

**Comment by controlcde** [comment]
I think you missed the same entry in the line 328.

**Comment by qiqizjl** [comment]
@controlcde   Thanks, Fixed

**Comment by qiqizjl** [comment]
@gboor Because fastcgi.conf is not included in the nginx image, fastcgi.conf is included in alpine.

**Comment by gboor** [comment]
So the alpine version works?

If that is true, I think the Dockerfiles for Debian need to change so that another tmpl can be injected.

**Comment by qiqizjl** [comment]
@gboor  yes.alpine version is ok .  If you want to use Debian, you can make corresponding changes based on the current PR. I think it can be normal operation.

**Comment by BlackSmith** [comment]
Hi folks, 
any progress with this problem?

**Comment by G1K** [comment]
very annoying bug. @jwilder accept the correction please
@qiqizjl look at the build errors please

**Comment by qiqizjl** [comment]
@G1K Fixed in #1124

**Comment by SerikK** [comment]
@qiqizjl index.php not opening by default

**Comment by TheLastProject** [comment]
Any reason this hasn't been merged yet?

**Comment by jwilder** [comment]
@TheLastProject  CI checks failed.  I kicked them off again, but PR might need to be rebased.

**Pull request merged**
