### PR TITLE
Added HTTPS_METHOD=nohttps to disable SSL site

### PR DESCRIPTION
**Pull request by kamermans**
This feature complements `HTTPS_METHOD=nohttp`, which disables the HTTP site.  For containers with `HTTPS_METHOD=nohttps` set, the template sets `is_https` to `false`, which treats everything as if there was no matching certificate.  

This solves issue #573, in which a user needs to disable the HTTPS site for a specific container with a subdomain that happens to match the SSL cert of another container.

A test has also been added to cover this directive.

### CODE REVIEW

**Comment by Lange** [comment]
I have this use case as well, and would love to see this PR merged!

**Comment by kachkaev** [comment]
@Lange for now you can use this trick: `CERT_NAME=` ([suggested by @wader](https://github.com/jwilder/nginx-proxy/issues/573#issuecomment-249412689)). I struggled with the same problem just now and this worked for me like a charm!

**Comment by kamermans** [comment]
@jwilder This build is failing because Travis-CI is running a newer version of Docker than the one specified in your `.travis.yml`.  We will need to do one of the following:

1. Add `--force-yes` to the `apt-get` command to force Travis to downgrade Docker to the version specified (currently `1.12.1-0~trusty`)
2. Change the required Docker version to a version that is available on Travis-CI without downgrading
3. Be less specific and just accept whatever version of Docker is available in the testing environment

I think it would be best to do 1 and 2, where we figure out the latest version in Travis, pin that one in `.travis.yml` and add the `--force-yes` flag to prevent this from happening in the future.

**Comment by kamermans** [comment]
Sure, I'll rebase and push today.

**Comment by jwilder** [comment]
Thanks @kamermans!

**Pull request merged**
