### PR TITLE
Fix vhost_default path

### PR DESCRIPTION
**Pull request by rschmukler**

### CODE REVIEW

**Comment by Cryszon** [comment]
This problem also seems to appear on lines 143 and 167 and makes defaults completely unusable.

**Comment by wader** [comment]
the exists checks for default server blocks config looks broken too.

https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L141
https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl#L167

**Comment by wader** [comment]
doh @Cryszon just said that

**Comment by jwilder** [comment]
Fixed via #252

**Pull request closed without merging**
