### PR TITLE
added rewrite for 'www'-prefixed requests

### PR DESCRIPTION
**Pull request by mko-x**
After several users claiming not serving proxy via 'www'-prefixed URLs, added rewrite rule to template.

### CODE REVIEW

**Comment by md5** [comment]
I'm :-1: on this behavior being a default as you've implemented it.

I'm neutral on it existing as a feature that's triggered in some way by the value of `VIRTUAL_HOST`.

**Comment by johnjelinek** [comment]
Ya, I'd prefer it to be configurable as an env var instead of hardcoded like this commit.

**Comment by johnjelinek** [comment]
Also a 301 instead of rewrite

**Comment by md5** [comment]
I suppose this and #92 are different things now that you point it out... So that's going to be even more confusing...

**Comment by thaJeztah** [comment]
Why not handle the redirects in the "back-end" server/container? In my experience redirects `www->no-www` or `no-www->www` really differ per-application, I'm not sure this is something to handle by the proxy (which should IMO just be "transparent")

**Comment by mko-x** [comment]
I don't know how to handle 'www.' prefixed requests in the backend if
they don't reach it due to nginx only listening for non-'www' ones. With
a 'www.' request the 503 at the top of the template will take place. 

Could you tell me how I could achieve that?

>From my point of view the most users of the provided services expect the
'www.' prefixed URLs to work just like the non-'www'  ones. I received a lot of claims about that. Additionally there are several browsers adding the 'www.' automatically.

Sebastiaan van Stijn <notifications@github.com> wrote:
> Why not handle the redirects in the "back-end" server/container? In my
> experience redirects `www->no-www` or `no-www->www` really differ
> per-application, I'm not sure this is something to handle by the proxy
> (which should IMO just be "transparent")
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jwilder/nginx-proxy/pull/98#issuecomment-74628460

-- 
Sent using Mailpile, Free Software from www.mailpile.is

**Comment by thaJeztah** [comment]
> I don't know how to handle 'www.' prefixed requests in the backend if they don't reach it due to nginx only listening for non-'www' ones.

You should be able to add both `www.` and `non-www` versions to your `VIRTUAL_HOST` environment var, for example;

    docker run --name my-website -d -e VIRTUAL_HOST=mysite.example.com,www.mysite.example.com nginx

The "my-website" container will now be accessible at both http://mysite.example.com and http://www.mysite.example.com

*Inside* the my-website container, you can handle what should happen for each (redirect one way or the other)

**Comment by jmillerdesign** [comment]
Yeah, this commit forces non-www, which is bad.

What about this? Does this make too many assumptions, or would it be helpful enough in a large majority of projects?
If VIRTUAL_HOST=mysite.example.com, then automatically also include www.mysite.example.com and redirect it to mysite.example.com.
If VIRTUAL_HOST=www.mysite.example.com, then automatically also include mysite.example.com and redirect it to www.mysite.example.com.
If VIRTUAL_HOST=mysite.example.com,www.mysite.example.com then don't do any redirects.

**Comment by thaJeztah** [comment]
> Does this make too many assumptions, or would it be helpful enough in a large majority of projects

It certainly wouldn't help *me*; thinking of `api.domain.com`, `static.domain.com` and other subdomains, sometimes pointing to a different container/back-end.

In general, I don't think a proxy should make *any* assumptions, unless I explicitly specify it in the config-file or there's a config-parameter to specify this.

just my 0.02

**Comment by mko-x** [comment]
Ah, thank you. 

Somehow I didn't think of configuring it within the VIRTUAL_HOST env var. I will give it a try and if it works like expected this pull request might be superfluous.

Anyway I agree with johnjelinek in the mentioned points here and #92 . 
- Solution should work with 'Moved Permanently' 301 
- For my IMHO not that uncommon usecase - provide an env var flag or similar to configure global redirect handling at will, reducing redundancy and improving readability at least a bit
- From #92 : To set a redirect policy - global flag may be some kind of enum 
´´´AUTO_REDIRECT_TARGET{
   www,
   non-www,
   custom,
   off
}´´´

Defaulting to 'off' for backwards compatibility. With following effects:
- www: redirect non-www to www
- non-www: redirect www to non-www
- custom: redirect with custom prefix, as an idea e.g. for APIs, CDNs or what I see once a while 'www8' at amazon urls if I remember correctly + new env var like 'AUTO_REDIRECT_CUSTOM_TARGET' to set the value, non-www will be redirected as well if not prefixed with the custom value
- off: as default the behaviour like it is now, no auto redirecting

If I find time, I would change that in my fork and create a new pull request. 

Maybe someone has another better solution, will wait a while for feedback.

**Comment by jmillerdesign** [comment]
I still think it could be fine to automatically redirect ```www.api.example.com``` to ```api.example.com```, if your ```VIRTUAL_HOST=api.example.com```. I can understand the points though that perhaps it shouldn't do anything automatically. I'd be OK with using some sort of ```AUTO_REDIRECT_TARGET``` flag if you'd prefer that.

**Comment by jwilder** [comment]
I think #106 should resolve this.  You can add `client_max_body_size` and the rewrite in the custom include now and have your container's `VIRTUAL_HOST` var be the list all the domains it should work with.

**Comment by johnjelinek** [comment]
LGTM!

**Pull request closed without merging**
