### PR TITLE
Fix tests by simply switching to TravisCI

### PR DESCRIPTION
**Pull request by thomasleveil**
Circle CI is now failing to run the tests.
But TravisCI is happily [passing](https://travis-ci.org/thomasleveil/nginx-proxy/builds/95237853) the test suite :smile_cat:

This PR switches from CircleCI to TravisCI

### CODE REVIEW

**Comment by thomasleveil** [comment]
I'm closing this PR since tests work again on CircleCI

**Comment by thomasleveil** [comment]
Reopening for #337

**Comment by baptistedonaux** [comment]
@thomasleveil Thanks !

**Comment by jwilder** [comment]
Can you rebase?

**Comment by thomasleveil** [comment]
rebased

**Comment by baptistedonaux** [comment]
@jwilder Binary unavailable https://godist.herokuapp.com/projects/ddollar/forego/releases/current/linux-amd64/forego

**Comment by jwilder** [comment]
I pulled this into #407 and updated it to use the latest docker.  Thanks @thomasleveil!

**Pull request closed without merging**
