### PR TITLE
add link to letsencrypt-nginx-proxy-companion

### PR DESCRIPTION
**Pull request by MichaelSp**

### CODE REVIEW

**Comment by mgcrea** [comment]
This docker image does not work anymore and the project seems unmaintained.

**Comment by MichaelSp** [comment]
I use it. Works quiet nice.

**Comment by matt-hh** [comment]
Good news: The maintainer has fixed the problem, it works again. https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion

**Comment by jwilder** [comment]
Thanks @MichaelSp!

**Pull request merged**
